int a = 5;
int b = 8;
int c = 1;
int d = 16;
int e = 3;
int max = a;
if (a>max) max = a; 
if (b>max) max = b; 
if (c>max) max = c; 
if (d>max) max = d; 
if (e>max) max = e; 
Console.Write("Максимальное значение это - ");
Console.WriteLine(max);